<!--
/**
 * Copyright © Alpina. All rights reserved.
 */
-->
<div class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Alpina Recipes and Articles Management')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="messages">
            <div class="message message-info">
                <div>
                    <?= $block->escapeHtml(__('Welcome to Alpina Recipes and Articles module. Content will be displayed here.')) ?>
                </div>
            </div>
        </div>
    </div>
</div>
